[phases.setup]
nixPkgs = [
  "chromium",
  "chromedriver",
  "nss",
  "fontconfig",
  "freetype",
  "libxkbcommon",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libXtst"
]
